/*----- PROTECTED REGION ID(PSDTexStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        PSDTexStateMachine.cpp
//
// description : State machine file for the PSDTex class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <PSDTex.h>

/*----- PROTECTED REGION END -----*/	//	PSDTex::PSDTexStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace PSDTex_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : PSDTex::is_image_allowed()
 *	Description : Execution allowed for image attribute
 */
//--------------------------------------------------------
bool PSDTex::is_image_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for image attribute in read access.
	/*----- PROTECTED REGION ID(PSDTex::imageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PSDTex::imageStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : PSDTex::is_Start_allowed()
 *	Description : Execution allowed for Start attribute
 */
//--------------------------------------------------------
bool PSDTex::is_Start_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Start command.
	/*----- PROTECTED REGION ID(PSDTex::StartStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PSDTex::StartStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PSDTex::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool PSDTex::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(PSDTex::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PSDTex::StopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : PSDTex::is_Clear_allowed()
 *	Description : Execution allowed for Clear attribute
 */
//--------------------------------------------------------
bool PSDTex::is_Clear_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Clear command.
	/*----- PROTECTED REGION ID(PSDTex::ClearStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PSDTex::ClearStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(PSDTex::PSDTexStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	PSDTex::PSDTexStateAllowed.AdditionalMethods

}	//	End of namespace
